package com.ExceptionHandlingsAssign;
//7. WAP to check can we have an empty catch block? 
public class Assign7 {

	public static void main(String[] args) {
		try
		{
			int a = 10 /5;
			
		}
		catch(ArithmeticException o)
		{
			o.printStackTrace();
		}

	}

}
